# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 346)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons8-pdf-filled-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolTip {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                background-color: #5A7566;\n"
"\n"
"                color: white;\n"
"\n"
"                padding: 0px; /*remove padding, for fix combobox tooltip.*/\n"
"\n"
"                opacity: 200;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QWidget {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                selection-background-color: #3daee9;\n"
"\n"
"                selection-color: #eff0f1;\n"
"\n"
"                background-clip: border;\n"
"\n"
"                border-image: none;\n"
"\n"
"                border: 0px transparent black;\n"
"\n"
"                outline: 0;\n"
"\n"
"                font: 25 12pt \"Gotham Book\";\n"
"\n"
"                }\n"
"\n"
"\n"
"                QWidget:item:hover {\n"
"\n"
"                background-color: #18465d;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QWidget:item:selected {\n"
"\n"
"                background-color: #18465d;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox {\n"
"\n"
"                spacing: 5px;\n"
"\n"
"                outline: none;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                margin-bottom: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox:disabled {\n"
"\n"
"                color: #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator,\n"
"\n"
"                QGroupBox::indicator {\n"
"\n"
"                width: 18px;\n"
"\n"
"                height: 18px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QGroupBox::indicator {\n"
"\n"
"                margin-left: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:unchecked,\n"
"\n"
"                QGroupBox::indicator:unchecked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:unchecked:hover,\n"
"\n"
"                QCheckBox::indicator:unchecked:focus,\n"
"\n"
"                QCheckBox::indicator:unchecked:pressed,\n"
"\n"
"                QGroupBox::indicator:unchecked:hover,\n"
"\n"
"                QGroupBox::indicator:unchecked:focus,\n"
"\n"
"                QGroupBox::indicator:unchecked:pressed {\n"
"\n"
"                border: none;\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:checked,\n"
"\n"
"                QGroupBox::indicator:checked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:checked:hover,\n"
"\n"
"                QCheckBox::indicator:checked:focus,\n"
"\n"
"                QCheckBox::indicator:checked:pressed,\n"
"\n"
"                QGroupBox::indicator:checked:hover,\n"
"\n"
"                QGroupBox::indicator:checked:focus,\n"
"\n"
"                QGroupBox::indicator:checked:pressed {\n"
"\n"
"                border: none;\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:indeterminate {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_indeterminate.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:indeterminate:focus,\n"
"\n"
"                QCheckBox::indicator:indeterminate:hover,\n"
"\n"
"                QCheckBox::indicator:indeterminate:pressed {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_indeterminate_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:checked:disabled,\n"
"\n"
"                QGroupBox::indicator:checked:disabled {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QCheckBox::indicator:unchecked:disabled,\n"
"\n"
"                QGroupBox::indicator:unchecked:disabled {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton {\n"
"\n"
"                spacing: 5px;\n"
"\n"
"                outline: none;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                margin-bottom: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton:disabled {\n"
"\n"
"                color: #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator {\n"
"\n"
"                width: 21px;\n"
"\n"
"                height: 21px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:unchecked {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:unchecked:hover,\n"
"\n"
"                QRadioButton::indicator:unchecked:focus,\n"
"\n"
"                QRadioButton::indicator:unchecked:pressed {\n"
"\n"
"                border: none;\n"
"\n"
"                outline: none;\n"
"\n"
"                image: url(:/qss_icons/rc/radio_unchecked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:checked {\n"
"\n"
"                border: none;\n"
"\n"
"                outline: none;\n"
"\n"
"                image: url(:/qss_icons/rc/radio_checked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:checked:hover,\n"
"\n"
"                QRadioButton::indicator:checked:focus,\n"
"\n"
"                QRadioButton::indicator:checked:pressed {\n"
"\n"
"                border: none;\n"
"\n"
"                outline: none;\n"
"\n"
"                image: url(:/qss_icons/rc/radio_checked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:checked:disabled {\n"
"\n"
"                outline: none;\n"
"\n"
"                image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QRadioButton::indicator:unchecked:disabled {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenuBar {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenuBar::item {\n"
"\n"
"                background: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenuBar::item:selected {\n"
"\n"
"                background: transparent;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenuBar::item:pressed {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                margin-bottom: -1px;\n"
"\n"
"                padding-bottom: 1px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                margin: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::icon {\n"
"\n"
"                margin: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::item {\n"
"\n"
"                padding: 5px 30px 5px 30px;\n"
"\n"
"                border: 1px solid transparent;\n"
"\n"
"                /* reserve space for selection border */\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::item:selected {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::separator {\n"
"\n"
"                height: 2px;\n"
"\n"
"                background: lightblue;\n"
"\n"
"                margin-left: 10px;\n"
"\n"
"                margin-right: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator {\n"
"\n"
"                width: 18px;\n"
"\n"
"                height: 18px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* non-exclusive indicator = check box style indicator\n"
"\n"
"                (see QActionGroup::setExclusive) */\n"
"\n"
"\n"
"                QMenu::indicator:non-exclusive:unchecked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:non-exclusive:unchecked:selected {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:non-exclusive:checked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:non-exclusive:checked:selected {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"\n"
"\n"
"                QMenu::indicator:exclusive:unchecked {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:exclusive:unchecked:selected {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:exclusive:checked {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_checked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::indicator:exclusive:checked:selected {\n"
"\n"
"                image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::right-arrow {\n"
"\n"
"                margin: 5px;\n"
"\n"
"                image: url(:/qss_icons/rc/right_arrow.png)\n"
"\n"
"                }\n"
"\n"
"\n"
"                QWidget:disabled {\n"
"\n"
"                color: #454545;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractItemView {\n"
"\n"
"                alternate-background-color: #181e1f;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #3A3939;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QWidget:focus,\n"
"\n"
"                QMenuBar:focus {\n"
"\n"
"                border: 1px solid #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabWidget:focus,\n"
"\n"
"                QCheckBox:focus,\n"
"\n"
"                QRadioButton:focus,\n"
"\n"
"                QSlider:focus {\n"
"\n"
"                border: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QLineEdit {\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border-style: solid;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractItemView QLineEdit {\n"
"\n"
"                padding: 0;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QGroupBox {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                margin-top: 20px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QGroupBox::title {\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                subcontrol-position: top center;\n"
"\n"
"                padding-left: 10px;\n"
"\n"
"                padding-right: 10px;\n"
"\n"
"                padding-top: 10px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractScrollArea {\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                background-color: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar:horizontal {\n"
"\n"
"                height: 15px;\n"
"\n"
"                margin: 3px 15px 3px 15px;\n"
"\n"
"                border: 1px transparent #2A2929;\n"
"\n"
"                border-radius: 4px;\n"
"\n"
"                background-color: #2A2929;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::handle:horizontal {\n"
"\n"
"                background-color: #605F5F;\n"
"\n"
"                min-width: 5px;\n"
"\n"
"                border-radius: 4px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-line:horizontal {\n"
"\n"
"                margin: 0px 3px 0px 3px;\n"
"\n"
"                border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"\n"
"                width: 10px;\n"
"\n"
"                height: 10px;\n"
"\n"
"                subcontrol-position: right;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::sub-line:horizontal {\n"
"\n"
"                margin: 0px 3px 0px 3px;\n"
"\n"
"                border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: left;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-line:horizontal:hover,\n"
"\n"
"                QScrollBar::add-line:horizontal:on {\n"
"\n"
"                border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: right;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::sub-line:horizontal:hover,\n"
"\n"
"                QScrollBar::sub-line:horizontal:on {\n"
"\n"
"                border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: left;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::up-arrow:horizontal,\n"
"\n"
"                QScrollBar::down-arrow:horizontal {\n"
"\n"
"                background: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-page:horizontal,\n"
"\n"
"                QScrollBar::sub-page:horizontal {\n"
"\n"
"                background: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar:vertical {\n"
"\n"
"                background-color: #2A2929;\n"
"\n"
"                width: 15px;\n"
"\n"
"                margin: 15px 3px 15px 3px;\n"
"\n"
"                border: 1px transparent #2A2929;\n"
"\n"
"                border-radius: 4px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::handle:vertical {\n"
"\n"
"                background-color: #605F5F;\n"
"\n"
"                min-height: 5px;\n"
"\n"
"                border-radius: 4px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::sub-line:vertical {\n"
"\n"
"                margin: 3px 0px 3px 0px;\n"
"\n"
"                border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: top;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-line:vertical {\n"
"\n"
"                margin: 3px 0px 3px 0px;\n"
"\n"
"                border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: bottom;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::sub-line:vertical:hover,\n"
"\n"
"                QScrollBar::sub-line:vertical:on {\n"
"\n"
"                border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: top;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-line:vertical:hover,\n"
"\n"
"                QScrollBar::add-line:vertical:on {\n"
"\n"
"                border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                height: 10px;\n"
"\n"
"                width: 10px;\n"
"\n"
"                subcontrol-position: bottom;\n"
"\n"
"                subcontrol-origin: margin;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::up-arrow:vertical,\n"
"\n"
"                QScrollBar::down-arrow:vertical {\n"
"\n"
"                background: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QScrollBar::add-page:vertical,\n"
"\n"
"                QScrollBar::sub-page:vertical {\n"
"\n"
"                background: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTextEdit {\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPlainTextEdit {\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                ;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section {\n"
"\n"
"                background-color: #76797C;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSizeGrip {\n"
"\n"
"                image: url(:/qss_icons/rc/sizegrip.png);\n"
"\n"
"                width: 12px;\n"
"\n"
"                height: 12px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMainWindow::separator {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                color: white;\n"
"\n"
"                padding-left: 4px;\n"
"\n"
"                spacing: 2px;\n"
"\n"
"                border: 1px dashed #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMainWindow::separator:hover {\n"
"\n"
"                background-color: #787876;\n"
"\n"
"                color: white;\n"
"\n"
"                padding-left: 4px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                spacing: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QMenu::separator {\n"
"\n"
"                height: 1px;\n"
"\n"
"                background-color: #76797C;\n"
"\n"
"                color: white;\n"
"\n"
"                padding-left: 4px;\n"
"\n"
"                margin-left: 10px;\n"
"\n"
"                margin-right: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QFrame {\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QFrame[frameShape=\"0\"] {\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px transparent #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QStackedWidget {\n"
"\n"
"                border: 1px transparent black;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBar {\n"
"\n"
"                border: 1px transparent #393838;\n"
"\n"
"                background: 1px solid #181e1f;\n"
"\n"
"                font-weight: bold;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBar::handle:horizontal {\n"
"\n"
"                image: url(:/qss_icons/rc/Hmovetoolbar.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBar::handle:vertical {\n"
"\n"
"                image: url(:/qss_icons/rc/Vmovetoolbar.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBar::separator:horizontal {\n"
"\n"
"                image: url(:/qss_icons/rc/Hsepartoolbar.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBar::separator:vertical {\n"
"\n"
"                image: url(:/qss_icons/rc/Vsepartoolbar.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton#qt_toolbar_ext_button {\n"
"\n"
"                background: #58595a\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border-width: 1px;\n"
"\n"
"                border-color: #76797C;\n"
"\n"
"                border-style: solid;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                outline: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton:disabled {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border-width: 1px;\n"
"\n"
"                border-color: #454545;\n"
"\n"
"                border-style: solid;\n"
"\n"
"                padding-top: 5px;\n"
"\n"
"                padding-bottom: 5px;\n"
"\n"
"                padding-left: 10px;\n"
"\n"
"                padding-right: 10px;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                color: #454545;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton:focus {\n"
"\n"
"                color: white;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton:pressed {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                padding-top: -15px;\n"
"\n"
"                padding-bottom: -17px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox {\n"
"\n"
"                selection-background-color: #3daee9;\n"
"\n"
"                border-style: solid;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                min-width: 75px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton:checked {\n"
"\n"
"                background-color: #76797C;\n"
"\n"
"                border-color: #6A6969;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox:hover,\n"
"\n"
"                QPushButton:hover,\n"
"\n"
"                QAbstractSpinBox:hover,\n"
"\n"
"                QLineEdit:hover,\n"
"\n"
"                QTextEdit:hover,\n"
"\n"
"                QPlainTextEdit:hover,\n"
"\n"
"                QAbstractView:hover,\n"
"\n"
"                QTreeView:hover {\n"
"\n"
"                border: 1px solid #3daee9;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox:on {\n"
"\n"
"                padding-top: 3px;\n"
"\n"
"                padding-left: 4px;\n"
"\n"
"                selection-background-color: #4a4a4a;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox QAbstractItemView {\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                selection-background-color: #18465d;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox::drop-down {\n"
"\n"
"                subcontrol-origin: padding;\n"
"\n"
"                subcontrol-position: top right;\n"
"\n"
"                width: 15px;\n"
"\n"
"                border-left-width: 0px;\n"
"\n"
"                border-left-color: darkgray;\n"
"\n"
"                border-left-style: solid;\n"
"\n"
"                border-top-right-radius: 3px;\n"
"\n"
"                border-bottom-right-radius: 3px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox::down-arrow {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QComboBox::down-arrow:on,\n"
"\n"
"                QComboBox::down-arrow:hover,\n"
"\n"
"                QComboBox::down-arrow:focus {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox {\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                min-width: 75px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox:up-button {\n"
"\n"
"                background-color: transparent;\n"
"\n"
"                subcontrol-origin: border;\n"
"\n"
"                subcontrol-position: center right;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox:down-button {\n"
"\n"
"                background-color: transparent;\n"
"\n"
"                subcontrol-origin: border;\n"
"\n"
"                subcontrol-position: center left;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox::up-arrow,\n"
"\n"
"                QAbstractSpinBox::up-arrow:disabled,\n"
"\n"
"                QAbstractSpinBox::up-arrow:off {\n"
"\n"
"                image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"\n"
"                width: 10px;\n"
"\n"
"                height: 10px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox::up-arrow:hover {\n"
"\n"
"                image: url(:/qss_icons/rc/up_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox::down-arrow,\n"
"\n"
"                QAbstractSpinBox::down-arrow:disabled,\n"
"\n"
"                QAbstractSpinBox::down-arrow:off {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"\n"
"                width: 10px;\n"
"\n"
"                height: 10px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QAbstractSpinBox::down-arrow:hover {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QLabel {\n"
"\n"
"                border: 0px solid black;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabWidget {\n"
"\n"
"                border: 0px transparent black;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabWidget::pane {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabWidget::tab-bar {\n"
"\n"
"                /* left: 5px; move to the right by 5px */\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar {\n"
"\n"
"                qproperty-drawBase: 0;\n"
"\n"
"                border-radius: 3px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar:focus {\n"
"\n"
"                border: 0px transparent black;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::close-button {\n"
"\n"
"                image: url(:/qss_icons/rc/close.png);\n"
"\n"
"                background: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::close-button:hover {\n"
"\n"
"                image: url(:/qss_icons/rc/close-hover.png);\n"
"\n"
"                background: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::close-button:pressed {\n"
"\n"
"                image: url(:/qss_icons/rc/close-pressed.png);\n"
"\n"
"                background: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* TOP TABS */\n"
"\n"
"\n"
"                QTabBar::tab:top {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-bottom: 1px transparent black;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                min-width: 50px;\n"
"\n"
"                border-top-left-radius: 2px;\n"
"\n"
"                border-top-right-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:top:selected {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #54575B;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-bottom: 2px solid #3daee9;\n"
"\n"
"                border-top-left-radius: 2px;\n"
"\n"
"                border-top-right-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:top:!selected:hover {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* BOTTOM TABS */\n"
"\n"
"\n"
"                QTabBar::tab:bottom {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-top: 1px transparent black;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border-bottom-left-radius: 2px;\n"
"\n"
"                border-bottom-right-radius: 2px;\n"
"\n"
"                min-width: 50px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:bottom:selected {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #54575B;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-top: 2px solid #3daee9;\n"
"\n"
"                border-bottom-left-radius: 2px;\n"
"\n"
"                border-bottom-right-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:bottom:!selected:hover {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* LEFT TABS */\n"
"\n"
"\n"
"                QTabBar::tab:left {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-left: 1px transparent black;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border-top-right-radius: 2px;\n"
"\n"
"                border-bottom-right-radius: 2px;\n"
"\n"
"                min-height: 50px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:left:selected {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #54575B;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-left: 2px solid #3daee9;\n"
"\n"
"                border-top-right-radius: 2px;\n"
"\n"
"                border-bottom-right-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:left:!selected:hover {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* RIGHT TABS */\n"
"\n"
"\n"
"                QTabBar::tab:right {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-right: 1px transparent black;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border-top-left-radius: 2px;\n"
"\n"
"                border-bottom-left-radius: 2px;\n"
"\n"
"                min-height: 50px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:right:selected {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #54575B;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-right: 2px solid #3daee9;\n"
"\n"
"                border-top-left-radius: 2px;\n"
"\n"
"                border-bottom-left-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar::tab:right:!selected:hover {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar QToolButton::right-arrow:enabled {\n"
"\n"
"                image: url(:/qss_icons/rc/right_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar QToolButton::left-arrow:enabled {\n"
"\n"
"                image: url(:/qss_icons/rc/left_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar QToolButton::right-arrow:disabled {\n"
"\n"
"                image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTabBar QToolButton::left-arrow:disabled {\n"
"\n"
"                image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDockWidget {\n"
"\n"
"                background: #181e1f;\n"
"\n"
"                border: 1px solid #403F3F;\n"
"\n"
"                titlebar-close-icon: url(:/qss_icons/rc/close.png);\n"
"\n"
"                titlebar-normal-icon: url(:/qss_icons/rc/undock.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDockWidget::close-button,\n"
"\n"
"                QDockWidget::float-button {\n"
"\n"
"                border: 1px solid transparent;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                background: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDockWidget::close-button:hover,\n"
"\n"
"                QDockWidget::float-button:hover {\n"
"\n"
"                background: rgba(255, 255, 255, 10);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDockWidget::close-button:pressed,\n"
"\n"
"                QDockWidget::float-button:pressed {\n"
"\n"
"                padding: 1px -1px -1px 1px;\n"
"\n"
"                background: rgba(255, 255, 255, 10);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView,\n"
"\n"
"                QListView {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView:branch:selected,\n"
"\n"
"                QTreeView:branch:hover {\n"
"\n"
"                background: url(:/qss_icons/rc/transparent.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:has-siblings:!adjoins-item {\n"
"\n"
"                border-image: url(:/qss_icons/rc/transparent.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:has-siblings:adjoins-item {\n"
"\n"
"                border-image: url(:/qss_icons/rc/transparent.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"\n"
"                border-image: url(:/qss_icons/rc/transparent.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:has-children:!has-siblings:closed,\n"
"\n"
"                QTreeView::branch:closed:has-children:has-siblings {\n"
"\n"
"                image: url(:/qss_icons/rc/branch_closed.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:open:has-children:!has-siblings,\n"
"\n"
"                QTreeView::branch:open:has-children:has-siblings {\n"
"\n"
"                image: url(:/qss_icons/rc/branch_open.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:has-children:!has-siblings:closed:hover,\n"
"\n"
"                QTreeView::branch:closed:has-children:has-siblings:hover {\n"
"\n"
"                image: url(:/qss_icons/rc/branch_closed-on.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::branch:open:has-children:!has-siblings:hover,\n"
"\n"
"                QTreeView::branch:open:has-children:has-siblings:hover {\n"
"\n"
"                image: url(:/qss_icons/rc/branch_open-on.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QListView::item:!selected:hover,\n"
"\n"
"                QTreeView::item:!selected:hover {\n"
"\n"
"                background: #18465d;\n"
"\n"
"                outline: 0;\n"
"\n"
"                color: #eff0f1\n"
"\n"
"                }\n"
"\n"
"\n"
"                QListView::item:selected:hover,\n"
"\n"
"                QTreeView::item:selected:hover {\n"
"\n"
"                background: #287399;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:checked,\n"
"\n"
"                QListView::indicator:checked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:unchecked,\n"
"\n"
"                QListView::indicator:unchecked {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:indeterminate,\n"
"\n"
"                QListView::indicator:indeterminate {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_indeterminate.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:checked:hover,\n"
"\n"
"                QTreeView::indicator:checked:focus,\n"
"\n"
"                QTreeView::indicator:checked:pressed,\n"
"\n"
"                QListView::indicator:checked:hover,\n"
"\n"
"                QListView::indicator:checked:focus,\n"
"\n"
"                QListView::indicator:checked:pressed {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_checked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:unchecked:hover,\n"
"\n"
"                QTreeView::indicator:unchecked:focus,\n"
"\n"
"                QTreeView::indicator:unchecked:pressed,\n"
"\n"
"                QListView::indicator:unchecked:hover,\n"
"\n"
"                QListView::indicator:unchecked:focus,\n"
"\n"
"                QListView::indicator:unchecked:pressed {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_unchecked_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTreeView::indicator:indeterminate:hover,\n"
"\n"
"                QTreeView::indicator:indeterminate:focus,\n"
"\n"
"                QTreeView::indicator:indeterminate:pressed,\n"
"\n"
"                QListView::indicator:indeterminate:hover,\n"
"\n"
"                QListView::indicator:indeterminate:focus,\n"
"\n"
"                QListView::indicator:indeterminate:pressed {\n"
"\n"
"                image: url(:/qss_icons/rc/checkbox_indeterminate_focus.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::groove:horizontal {\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                height: 4px;\n"
"\n"
"                background: #565a5e;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::handle:horizontal {\n"
"\n"
"                background: #232629;\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                width: 16px;\n"
"\n"
"                height: 16px;\n"
"\n"
"                margin: -8px 0;\n"
"\n"
"                border-radius: 9px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::sub-page:horizontal {\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                height: 4px;\n"
"\n"
"                background: #3daee9;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::groove:vertical {\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                width: 4px;\n"
"\n"
"                background: #565a5e;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                border-radius: 3px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::handle:vertical {\n"
"\n"
"                background: #232629;\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                width: 16px;\n"
"\n"
"                height: 16px;\n"
"\n"
"                margin: 0 -8px;\n"
"\n"
"                border-radius: 9px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSlider::sub-page:vertical {\n"
"\n"
"                border: 1px solid #565a5e;\n"
"\n"
"                width: 4px;\n"
"\n"
"                background: #3daee9;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                border-radius: 3px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton {\n"
"\n"
"                background-color: transparent;\n"
"\n"
"                border: 1px transparent #76797C;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                margin: 3px;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton[popupMode=\"1\"] {\n"
"\n"
"                /* only for MenuButtonPopup */\n"
"\n"
"                padding-right: 20px;\n"
"\n"
"                /* make way for the popup button */\n"
"\n"
"                border: 1px #76797C;\n"
"\n"
"                border-radius: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton[popupMode=\"2\"] {\n"
"\n"
"                /* only for InstantPopup */\n"
"\n"
"                padding-right: 10px;\n"
"\n"
"                /* make way for the popup button */\n"
"\n"
"                border: 1px #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton:hover,\n"
"\n"
"                QToolButton::menu-button:hover {\n"
"\n"
"                background-color: transparent;\n"
"\n"
"                border: 1px solid #3daee9;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton:checked,\n"
"\n"
"                QToolButton:pressed,\n"
"\n"
"                QToolButton::menu-button:pressed {\n"
"\n"
"                background-color: #3daee9;\n"
"\n"
"                border: 1px solid #3daee9;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* the subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"\n"
"\n"
"                QToolButton::menu-indicator {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                top: -7px;\n"
"\n"
"                left: -2px;\n"
"\n"
"                /* shift it a bit */\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"\n"
"\n"
"                QToolButton::menu-button {\n"
"\n"
"                border: 1px transparent #76797C;\n"
"\n"
"                border-top-right-radius: 6px;\n"
"\n"
"                border-bottom-right-radius: 6px;\n"
"\n"
"                /* 16px width + 4px for border = 20px allocated above */\n"
"\n"
"                width: 16px;\n"
"\n"
"                outline: none;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton::menu-arrow {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolButton::menu-arrow:open {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QPushButton::menu-indicator {\n"
"\n"
"                subcontrol-origin: padding;\n"
"\n"
"                subcontrol-position: bottom right;\n"
"\n"
"                left: 8px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTableView {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                gridline-color: #181e1f;\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTableView,\n"
"\n"
"                QHeaderView {\n"
"\n"
"                border-radius: 0px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTableView::item:pressed,\n"
"\n"
"                QListView::item:pressed,\n"
"\n"
"                QTreeView::item:pressed {\n"
"\n"
"                background: #18465d;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTableView::item:selected:active,\n"
"\n"
"                QTreeView::item:selected:active,\n"
"\n"
"                QListView::item:selected:active {\n"
"\n"
"                background: #287399;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border: 1px transparent;\n"
"\n"
"                border-radius: 0px;\n"
"\n"
"                margin: 0px;\n"
"\n"
"                padding: 0px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-radius: 0px;\n"
"\n"
"                text-align: center;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section::vertical::first,\n"
"\n"
"                QHeaderView::section::vertical::only-one {\n"
"\n"
"                border-top: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section::vertical {\n"
"\n"
"                border-top: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section::horizontal::first,\n"
"\n"
"                QHeaderView::section::horizontal::only-one {\n"
"\n"
"                border-left: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section::horizontal {\n"
"\n"
"                border-left: transparent;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::section:checked {\n"
"\n"
"                color: white;\n"
"\n"
"                background-color: #334e5e;\n"
"\n"
"                }\n"
"\n"
"\n"
"                /* style the sort indicator */\n"
"\n"
"\n"
"                QHeaderView::down-arrow {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QHeaderView::up-arrow {\n"
"\n"
"                image: url(:/qss_icons/rc/up_arrow.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QTableCornerButton::section {\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border: 1px transparent #76797C;\n"
"\n"
"                border-radius: 0px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBox {\n"
"\n"
"                padding: 5px;\n"
"\n"
"                border: 1px transparent black;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBox::tab {\n"
"\n"
"                color: #eff0f1;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-bottom: 1px transparent #181e1f;\n"
"\n"
"                border-top-left-radius: 5px;\n"
"\n"
"                border-top-right-radius: 5px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QToolBox::tab:selected {\n"
"\n"
"                /* italicize selected tabs */\n"
"\n"
"                font: italic;\n"
"\n"
"                background-color: #181e1f;\n"
"\n"
"                border-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QStatusBar::item {\n"
"\n"
"                border: 0px transparent dark;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QFrame[height=\"3\"],\n"
"\n"
"                QFrame[width=\"3\"] {\n"
"\n"
"                background-color: #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSplitter::handle {\n"
"\n"
"                border: 1px dashed #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSplitter::handle:hover {\n"
"\n"
"                background-color: #787876;\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSplitter::handle:horizontal {\n"
"\n"
"                width: 1px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QSplitter::handle:vertical {\n"
"\n"
"                height: 1px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QProgressBar {\n"
"\n"
"                border: 1px solid #76797C;\n"
"\n"
"                border-radius: 5px;\n"
"\n"
"                text-align: center;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QProgressBar::chunk {\n"
"\n"
"                background-color: #05B8CC;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit {\n"
"\n"
"                selection-background-color: #3daee9;\n"
"\n"
"                border-style: solid;\n"
"\n"
"                border: 1px solid #3375A3;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                padding: 1px;\n"
"\n"
"                min-width: 75px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit:on {\n"
"\n"
"                padding-top: 3px;\n"
"\n"
"                padding-left: 4px;\n"
"\n"
"                selection-background-color: #4a4a4a;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit QAbstractItemView {\n"
"\n"
"                background-color: #232629;\n"
"\n"
"                border-radius: 2px;\n"
"\n"
"                border: 1px solid #3375A3;\n"
"\n"
"                selection-background-color: #3daee9;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit::drop-down {\n"
"\n"
"                subcontrol-origin: padding;\n"
"\n"
"                subcontrol-position: top right;\n"
"\n"
"                width: 15px;\n"
"\n"
"                border-left-width: 0px;\n"
"\n"
"                border-left-color: darkgray;\n"
"\n"
"                border-left-style: solid;\n"
"\n"
"                border-top-right-radius: 3px;\n"
"\n"
"                border-bottom-right-radius: 3px;\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit::down-arrow {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"\n"
"                }\n"
"\n"
"\n"
"                QDateEdit::down-arrow:on,\n"
"\n"
"                QDateEdit::down-arrow:hover,\n"
"\n"
"                QDateEdit::down-arrow:focus {\n"
"\n"
"                image: url(:/qss_icons/rc/down_arrow.png);\n"
"\n"
"                }\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pin = QtWidgets.QPushButton(self.centralwidget)
        self.pin.setMinimumSize(QtCore.QSize(0, 50))
        self.pin.setStyleSheet("image: url(:/icons/icons8-pin-50.png);")
        self.pin.setText("")
        self.pin.setObjectName("pin")
        self.verticalLayout_4.addWidget(self.pin, 0, QtCore.Qt.AlignBottom)
        self.unpin = QtWidgets.QPushButton(self.centralwidget)
        self.unpin.setMinimumSize(QtCore.QSize(0, 50))
        self.unpin.setStyleSheet("image: url(:/icons/icons8-unpin-50.png);")
        self.unpin.setText("")
        self.unpin.setObjectName("unpin")
        self.verticalLayout_4.addWidget(self.unpin, 0, QtCore.Qt.AlignTop)
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setStyleSheet("image: url(:/icons/icons8-sort-up-filled-50.png);")
        self.up.setText("")
        self.up.setObjectName("up")
        self.verticalLayout_4.addWidget(self.up)
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setStyleSheet("image: url(:/icons/icons8-sort-down-filled-50.png);")
        self.down.setText("")
        self.down.setObjectName("down")
        self.verticalLayout_4.addWidget(self.down)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.page_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.page_edit.setObjectName("page_edit")
        self.gridLayout_3.addWidget(self.page_edit, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 8, 0, 1, 3)
        self.split_button = QtWidgets.QPushButton(self.centralwidget)
        self.split_button.setMinimumSize(QtCore.QSize(0, 50))
        self.split_button.setStyleSheet("image: url(:/icons/icons8-cut-paper-filled-50.png);")
        self.split_button.setText("")
        self.split_button.setObjectName("split_button")
        self.gridLayout.addWidget(self.split_button, 9, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setObjectName("file_list")
        self.gridLayout.addWidget(self.file_list, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PdfSplitter"))
        self.label.setText(_translate("MainWindow", "Pages"))

import icons_rc
